### ISSUE TITLE
cant upload scketch to Arduino dock 2

### ISSUE THREAD

**Issue by xyzbilal** [OnionIoT/Onion-Arduino-Library#2]
hi,
I m trying to upload a sketch to arduino dock 2 via omega 2+ as instructed this link https://docs.onion.io/omega2-docs/flash-arduino-dock-wirelessly.html#flash-arduino-dock-wirelessly and unfortunatelly arduino dock led s turn off s. then I tried instructions for omega at the link of https://wiki.onion.io/Tutorials/Arduino-Dock/Using-the-Arduino-Dock#the-onion-arduino-library with onion library and result same. there is no problem with connection. I get errors while uploading. as you will see at picture. getting error flash not successfull and other errors I cant relate.. regards..
![dock error](https://cloud.githubusercontent.com/assets/18241412/23864972/d06d6d7e-081c-11e7-8bc9-54ac406614bf.jpg)
and I tried to upload manually as instructed link https://docs.onion.io/omega2-docs/flash-arduino-dock-wirelessly.html section Manually Flashing on the Command line and get errors seen in thi pic below

![manuel error](https://cloud.githubusercontent.com/assets/18241412/23866981/1e52c22c-0823-11e7-90d6-ddb90e1364d6.jpg)

**Comment by greenbreakfast** [comment]
Looks like there's some issue with how the Arduino Dock software was installed on your Omega.

Please try [factory resetting your Omega](https://docs.onion.io/omega2-docs/factory-reset.html), and then installing the Arduino Dock package and trying again:
```
opkg update
opkg install arduino-dock-2
```

**Comment by xyzbilal** [comment]
Thanks Greenbreakfast. I made factory reset and upgrade onion. Made fresh install required packets then problem solved.
